# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^publication/|CHANGELOG.md|docs/index.md|.github/pull_request_template.md|resources/report-table-formatter.js|resources/lineage-variant-table-formatter.js"

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^config/multiqc_config_lab.yaml|.tests/config/multiqc_config_lab.yaml
      - id: check-added-large-files
      - id: no-commit-to-branch

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.6.0
    hooks:
      - id: snakefmt

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
        args: [-c, .markdownlint.yaml]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
