pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
limit-strain-genomes: 5

data-handling:
  # path of incoming data
  incoming: ../incoming/
  # path to store data in the workflow
  data: data/
  # path to archive data from incoming to
  archive: ../archive/

variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100
  filters:
    low-impact: 'ANN["IMPACT"] in ["LOW", "MODIFIER"]'
    high+moderate-impact: 'ANN["IMPACT"] in ["HIGH", "MODERATE"]'
    
  
strain-calling:
  # minimum reported strain fraction after quantification
  min-fraction: 0.02

  # paths to strain genomes that shall be used for quantification
  genomes:
    - resources/genomes/main.fasta
    - ../strain-genomes/hCoV-19BrazilSP-142020.fasta
    - ../strain-genomes/hCoV-19EnglandMILK-9E2FE02020.fasta
    - ../strain-genomes/hCoV-19JapanIC-05612021.fasta
    - ../strain-genomes/hCoV-19South_AfricaKRISP-K0043122020.fasta


adapters:
  #  Illumina TruSeq adapters
  illumina: "--adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"