pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
limit-strain-genomes: 100

variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100