pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
testing:
  limit-strain-genomes: 5
  benchmark-genomes:
    - MT971460
    - MT810976
    - MW184368
    - MT470120
    - MT451810
      # flag for using genomes from genbank. Only for benchmarking purposes.
  use-genbank: False



# genome to use as reference. Must be a NCBI accession
virus-reference-genome:
  - NC_045512.2


# download path of human genome reference
human-genome-download-path:
  - ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GCA_000001405.28_GRCh38.p13_genomic.fna.gz


data-handling:
  # path of incoming data
  incoming: ../incoming/
  # path to store data in the workflow
  data: data/
  # path to archive data from incoming to
  archive: ../archive/


RKI-quality-criteria:
  illumina:
    # minimal length of acceptable reads
    min-length-reads: 30
    # average quality of acceptable reads (PHRED)
    min-PHRED: 20
  ont:
    # minimal length of acceptable reads
    min-length-reads: 200
    # average quality of acceptable reads (PHRED)
    min-PHRED: 10
  # identity to NC_045512.22 of reconstructed genome
  min-identity: 0.9
  # share N in the reconstructed genome
  max-n: 0.05
  # minimum local sequencing depth without filtering of PCR duplicates
  min-depth-with-PCR-duplicates: 20
  # minimum local sequencing depth after filtering PCR duplicates
  min-depth-without-PCR-duplicates: 10
  # minimum informative allele frequency
  min-allele: 0.9
  # frameshift-Mutationen


variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100
  filters:
    low-impact: 'ANN["IMPACT"] in ["LOW", "MODIFIER"]'
    high+moderate-impact: 'ANN["IMPACT"] in ["HIGH", "MODERATE"]'


assembly:
  # minimum posterior probability for a clonal variant to be included in the generated pseudoassembly
  min-variant-prob: 0.95


strain-calling:
  # minimum reported strain fraction after quantification
  min-fraction: 0.02
  # paths to store genomes that are extracted from the full GISAID data
  extracted-strain-genomes: resources/genomes
  # flag for using all lineage reference from GISAIDS Epicov database. API key must be exported as env var GISAID_API_TOKEN.
  use-gisaid: True
  # GenBank accession for downloading lineage-references
  # only used, if use-gisaid flag is set to False
  lineage-references:
    B.1.1.7: MZ773928
    B.1.351: MZ433432
    P.1: MZ477759
    B.1.617.2: OK091006

adapters:
  #  Illumina TruSeq adapters
  illumina-revelo: "--adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  illumina-nimagen: "--adapter_sequence GCGAATTTCGACGATCGTTGCATTAACTCGCGAA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  amplicon-primers: "resources/primer.bedpe"
  amplicon-reference: "MN908947"

rki-output:
# minimum contig length
  minimum-length: 20000


# NCBI reference sequences of non-SARS-CoV-2 coronavirus. 
# Used to test whether the pipeline can distinguish between 
# non-SARS CoV-2 and SARS CoV-2 viruses.
non_cov2_genomes:
  - NC_005831
  - NC_002645
  - NC_006213
  - NC_006577
  - NC_019843
  # - NC_004718

# For testing the read bases strain calling
mixtures:
  # maximal number of reads to generate
  max_reads: 294459
  # number of mixtures to generate
  no_mixtures: 500
  # number of strains to mix
  no_strains: 2
  # or you can specify the mix you would like to have 
  # this assumes, that strain files are available under resources/genomes
  # the used number of strains must match the no_strains defined above
  use_predefined_mixtures: True
  # use the following format: "_MIX_B-1-1-7_PERC_90_MIX_B-1-351_PERC_10"
  predefined_mixtures:
    - "_MIX_B-1-1-7_PERC_50_MIX_B-1-351_PERC_50"
    - "_MIX_B-1-1-7_PERC_90_MIX_B-1-351_PERC_10"

# variants of concern (protein name -> variants)
voc:
  S:
    - N501Y
    - E484K
    - K417N
    - H69_V70del
  
# assemblers used for assembly comparison
assemblers_for_comparison:
  - megahit-std
  - megahit-meta-large
  - megahit-meta-sensitive
  - trinity
  - velvet
  - metaspades
  - coronaspades
  - spades
  - rnaviralspades

# assemblers used for sequencing method 
assemblers_used:
  shotgun: "megahit-std"
  amplicon: "metaspades"