pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
limit-strain-genomes: 5

data-handling:
  # path of incoming data
  incoming: ../incoming/
  # path to store data in the workflow
  data: data/
  # path to archive data from incoming to
  archive: ../archive/

variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100
  filters:
    low-impact: 'ANN["IMPACT"] in ["LOW", "MODIFIER"]'
    high+moderate-impact: 'ANN["IMPACT"] in ["HIGH", "MODERATE"]'

strain-calling:
  # minimum reported strain fraction after quantification
  min-fraction: 0.02
  # flag for using gisaid or genbank 
  use-gisaid: False
  # path to meta data from GISAID
  gisaid-metadata: resources/gisaid/metadata_2021-02-09_18-08.tsv
  # path to sequences fasta from GISAID
  gisaid-metafasta: resources/gisaid/sequences_2021-02-09_08-13.fasta
  # paths to store genomes that are extracted from the full GISAID data
  extracted-strain-genomes: resources/genomes

adapters:
  #  Illumina TruSeq adapters
  illumina: "--adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"