pepfile: benchmarking/config/samples/config.yaml

preprocessing:
  amplicon-primers: "resources/nCoV-2019.primer.bed"
  amplicon-reference: "MN908947"

medaka_model: r941_min_fast_g303

kit-adapters: "--adapter_sequence GCGAATTTCGACGATCGTTGCATTAACTCGCGAA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
