name: Publish Release to Registry

on:    
  release:
      types: [published]
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Dockerfile
      uses: snakemake/snakemake-github-action@v1.20.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--containerize > Dockerfile"

    - name: Publish to Registry
      pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
        dockerfile: Dockerfile