name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SetUp Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Update Contributing
        run: cat CONTRIBUTING.md > docs/dev-guide/contributing.md

      - name: Update Changelog
        run: cat CHANGELOG.md > docs/about/changelog.md

      - name: Update License
        run: cat LICENSE > docs/about/license.md

      - name: Install Dependencies
        run: pip install mkdocs-material

      - name: Publish Docs
        run: mkdocs gh-deploy --force
