name: Publish to Registry

on:    
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Create Dockerfile
      uses: snakemake/snakemake-github-action@v1.20.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--containerize > Dockerfile"

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: my-app
        tags: latest ${{ github.sha }}
        dockerfiles: |
          ./Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: uncovar/uncovar
        username: uncovar+robot
        password: ${{ secrets.QUAYIO_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
