on:
  push:
    branches:
      - main
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: release-please-action

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Change containerized tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sed -i "/containerized/c\containerized: \"quay.io/uncovar/uncovar:${{ steps.release.outputs.tag_name }}\"" workflow/Snakefile 
