on:
  push:
    branches:
      - main
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: release-please-action

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Export version as environment variable
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "VERSION=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}" >> $GITHUB_ENV
          echo "Version: ${{ env.VERSION }}"
      
      - name: Checkout release PR
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
          git fetch origin
          git checkout pr/${{ steps.release.outputs.pr }}

      - name: Change containerized tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sed -i "/containerized/c\containerized: \"quay.io/uncovar/uncovar#${{ env.VERSION }}\"" workflow/Snakefile

      - name: Push changed containerized tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git add workflow/Snakefile
          git commit -m "Changed containerized tag to ${{ env.VERSION }}"
          git push
