name: Release

on:
  push:
    branches:
      - master
      
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if PR is created
        id: pr_created
        run: |
          if [[ ${{ steps.release.outputs.pr }} =~ ^[0-9]+$ ]]
            then
              echo "::set-output name=pr::$(echo true)"
            else
              echo "::set-output name=pr::$(echo false)"
          fi
          
      - uses: actions/checkout@v2
        if: ${{ steps.pr_created.outputs.pr }}

      - name: Checkout release PR locally
        if: ${{ steps.pr_created.outputs.pr }} && ${{ !steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git fetch origin
          git pull origin pull/${{ steps.release.outputs.pr }}/head

      - name: Export version as environment variable
        if: ${{ steps.pr_created.outputs.pr }} && ${{ !steps.release.outputs.release_created }}
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "Version: ${{ env.VERSION }}"
          echo ${{ steps.release.outputs.tag_name }}
      
      - name: Switch to release PR on origin
        if: ${{ steps.pr_created.outputs.pr }} && ${{ !steps.release.outputs.release_created }}
        run: |
          git checkout release-v${{ env.VERSION }}

      - name: Change containerized tag
        if: ${{ steps.pr_created.outputs.pr }} && ${{ !steps.release.outputs.release_created }}
        run: |
          sed -i "/containerized/c\containerized: \"quay.io/uncovar/uncovar#${{ env.VERSION }}\"" workflow/Snakefile

      - name: Push changed containerized tag
        if: ${{ steps.pr_created.outputs.pr }} && ${{ !steps.release.outputs.release_created }}
        run: |
          git add workflow/Snakefile
          git commit -m "Changed containerized tag to ${{ env.VERSION }}"
          git push

      - name: Create dockerfile
        if: ${{ steps.release.outputs.release_created }}
        uses: snakemake/snakemake-github-action@v1.20.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--containerize > Dockerfile"

      - name: Build image
        if: ${{ steps.release.outputs.release_created }}
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: uncovar
          tags: latest ${{ github.sha }} ${{ env.VERSION }}
          dockerfiles: |
            ./Dockerfile

      - name: Push to quay.io
        if: ${{ steps.release.outputs.release_created }}
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: uncovar/uncovar
          username: uncovar+robot
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: Print image url
        if: ${{ steps.release.outputs.release_created }}
        run: echo "Release image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
